### ISSUE TITLE
Karol small knight title edit request

### ISSUE THREAD

**Issue by chrcoluk** [hueyyeng/VesperiaGuide#4]
Hi guys, great work on updating this guide.

But there is an error that could make people to do a ng+.

Karols small night title in the guide it states the following.

"With the Letter of Challenge (H. Blades) 2 and if you have cleared Tag Team Tournament - Challenger at the Arena, you will unlock Tag Team Tournament - Hero. If you don't have Karol and Raven in the Active Party, you will fight them in Tag Team Tournament - Hero (PS3 and Definitive Edition)"

I suggest to add below it.

Clear Tag Team Tournament - Hero "**Without**" Karol in the party, you MUST not fight it at all with Karol in the party, make a save before doing this fight.  When you defeat the challenge you should be awarded Karol's Small Knight title.  If you do this fight even once with Karol in the parry, you will not be able to obtain the title on this playthru unless you can go back to an older save.

**Comment by hueyyeng** [comment]
Hey there! Would you like to make a pull request for this?

I need to check my non NG+ saves if I have the Small Knight (I think I have it as I remember having that helmet costume).

**Comment by chrcoluk** [comment]
I am not sure how to do pull requests on github, but I will try and figure it out.

**Comment by chrcoluk** [comment]
#5

**Comment by hueyyeng** [comment]
Already merged into Master branch through pull request #5
